# Generated by Django 5.0.4 on 2024-04-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicalsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicaldata',
            old_name='patinet',
            new_name='patient',
        ),
    ]
